# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.3-node-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./venv
            - vendor/bundle
          key: dependencies-{{ checksum "Gemfile.lock" }}
        
      # Database setup
      - run: RAILS_ENV=test bundle exec rake db:create
      - run: RAILS_ENV=test bundle exec rake db:schema:load

      # run tests!
      - run:
          name: run tests
          command: |
            bundle exec rspec
          
      # Deploy sandbox
      - deploy:
          command: |
            # if [ "${CIRCLE_BRANCH}" == "develop" ];
            #   then bundle exec cap sandbox deploy
            # fi
          
      # Deploy staging
      - deploy:
          command: |
            # if [ "${CIRCLE_BRANCH}" == "staging" ];
            #   then bundle exec cap staging deploy
            # fi
          
      # Deploy production
      - deploy:
          command: |
            # if [ "${CIRCLE_BRANCH}" == "master" ];
            #   then bundle exec cap production deploy
            # fi